[package]
name = "luffylol/behavior-tree"
version = "0.1.4"
description = "Fork of Behavior Trees 5 (adds pre-emption) for Roblox (creator/runtime)"
license = "MIT"
realm = "shared"                # "server" or "client" if you want to restrict
registry = "https://github.com/UpliftGames/wally-index"

include = [
  "wally.toml",
  "behavior-tree/init.lua",
  "behavior-tree/BehaviorTree5.luau",
  "behavior-tree/BehaviorTreeCreator.luau",
  "default.project.json"
]

exclude = [ "rokit.toml", "selene.toml", "README.md" ]

[dependencies]

[dev-dependencies]
